[env:upesy_wroom]
platform = espressif32
board = esp32dev
framework = arduino

upload_port = COM3
monitor_port = COM3
monitor_speed = 115200

lib_deps =
    bblanchon/ArduinoJson
    knolleary/PubSubClient
    